Conference/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from conference.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('profile', ProfileDetailView.as_view()),
    path('profile/<int:user_id>', ProfileDetailView.as_view()),
    path('profile/edit', ProfileEditView.as_view()),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('presentations/all', AllPresentationsListView.as_view()),
    path('presentations/create', PresentationCreateView.as_view()),
    path('presentations/<int:event_id>', PresentationDetailView.as_view()),
    path('presentations/my', PresentationsListView.as_view()),
    path('presentations/<int:event_id>/edit', PresentationUpdateView.as_view()),
    path('presentations/<int:event_id>/signup', event_signup),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('schedules/', ScheduleList.as_view(), name='schedules-list'),
    path('schedules/<int:room_number>/', ScheduleDetail.as_view(), name='schedule-detail'),
    path('rooms/<int:pk>/', RoomDetail.as_view(), name='room-detail'),
    path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
    path('groups/<int:pk>', GroupDetail.as_view(), name='group-detail')

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

Conferences/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

from conference.views import HomeView, ProfileDetailView, ProfileEditView, RegisterFormView, AllPresentationsListView, \
    PresentationCreateView, PresentationDetailView, PresentationsListView, PresentationUpdateView, event_signup, \
    ScheduleList, ScheduleDetail, RoomDetail, UserDetail, GroupDetail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('profile', ProfileDetailView.as_view()),
    path('profile/<int:user_id>', ProfileDetailView.as_view()),
    path('profile/edit', ProfileEditView.as_view()),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('presentations/all', AllPresentationsListView.as_view()),
    path('presentations/create', PresentationCreateView.as_view()),
    path('presentations/<int:event_id>', PresentationDetailView.as_view()),
    path('presentations/my', PresentationsListView.as_view()),
    path('presentations/<int:event_id>/edit', PresentationUpdateView.as_view()),
    path('presentations/<int:event_id>/signup', event_signup),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('schedules/', ScheduleList.as_view(), name='schedules-list'),
    path('schedules/<int:room_number>/', ScheduleDetail.as_view(), name='schedule-detail'),
    path('rooms/<int:pk>/', RoomDetail.as_view(), name='room-detail'),
    path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
    path('groups/<int:pk>', GroupDetail.as_view(), name='group-detail')

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

conference/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Room(models.Model):
    number = models.IntegerField()
    address = models.CharField(max_length=125)

    def __str__(self):
        return f"Room #{self.number} at {self.address}"


class Schedule(models.Model):
    room = models.OneToOneField(Room, on_delete=models.CASCADE, null=True, blank=True)

    @receiver(post_save, sender=Room)
    def create_room_schedule(sender, instance, created, **kwargs):
        if created:
            Schedule.objects.create(room=instance)

    def __str__(self):
        return f"Schedule for room #{self.room.number}"


class Presentation(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, blank=True, null=True)
    presenters = models.ManyToManyField(User, blank=True)
    datetime = models.DateTimeField()
    title = models.CharField(max_length=125)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    description = models.CharField(max_length=350, default="")

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        schedule = Schedule.objects.filter(room=self.room)[0]
        self.schedule = schedule
        self.save_base()

    def __str__(self):
        return f"Presentation {self.title}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    attend_presentations = models.ManyToManyField(Presentation, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return f"Profile {self.user.first_name} {self.user.last_name}"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <title>{% block title %}Conference{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    ul.bar {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #333;
    }

    li.bar_element {
      float: left;
    }

    li.bar_element a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    /* Change the link color to #111 (black) on hover */
    li.bar_element a:hover {
      background-color: #009933;
    }

    body,
    html {
      height: 100%;
    }

    * {
      padding: 0;
      margin: 0;
    }

    .bg {
      /* The image used */
      background-image: url("https://raw.githubusercontent.com/LilJohny/Conference/master/static/images/91.jpg");

      /* Full height */
      height: 100%;

      /* Center and scale the image nicely */
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }

    .alert {
      font-size: 100px;
      color: darkred;
    }

    label {
      color: white;
    }
      {% block styles %}
      {% endblock %}
  </style>
</head>

<body>


  <ul class="bar">
    <li class="bar_element"><a href="/" class="active">Recent events</a></li>
    <li class="bar_element"><a href="/presentations/all">All Events</a></li>
    {% if user.is_authenticated %}
      <li class="bar_element"><a href="/profile">My profile</a></li>
    {% endif %}
    {% block rightbar %}{% endblock %}
  </ul>
  <div class="bg">
    {% block content %}
    <div style="padding-left:16px">
      <h2>Responsive Login Form in Navbar</h2>
      <p>Navigation menu with a login form and a submit button inside of it.</p>
      <p>Resize the browser window to see the responsive effect.</p>
    </div>
    {% endblock %}

  </div>
</body>

</html>

templates/event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% title %}</title>
</head>
<body>
    <h1>Conference {% title %}</h1>
    <h2>Lecturer: {% lecturer_name %}</h2>
    <h2>When: {% date %}</h2>
    <h2>Where: {% place %}</h2>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Conference{% endblock %}

{% block rightbar %}
{% if user.is_authenticated %}

    <li style="float:right" class="bar_element"><a class="active">Signed as {{ user.username }}</a></li>
    <li style="float:right" class="bar_element"><a href="{% url 'logout' %}">Sign Out</a></li>
    {% if creator %}
        <li style="float:right" class="bar_element"><a href="/presentations/create">Create presentation</a></li>
        <li style="float:right" class="bar_element"><a href="/presentations/my">My presentations</a></li>
        {% endif %}
{% else %}
    <li style="float:right" class="bar_element"><a class="active">You are not logged in</a></li>
    <li style="float:right" class="bar_element"><a href="{% url 'login' %}">Sign In</a></li>
    <li style="float:right" class="bar_element"><a href="/accounts/register">New user? Sign up</a></li>

{% endif %}
{% endblock %}
{% block content %}
<div class="container">
  <h2>Recent Events</h2>
  <ul class="list-group">
      {% for event in events %}
          <li class="list-group-item"><a href="/presentations/{{ event.id }}">{{event.title}}  on {{event.datetime}}</a></li>
      {% endfor %}
  </ul>
</div>
{% endblock %}

templates/presentation_all.html
{% extends 'index.html' %}
{% load conference_extras %}
{% block content %}
    {% for room in rooms %}
        <div class="container">
            <h2 style="color: whitesmoke">Room #{{ room.number }} at {{ room.address }}</h2>
            <ul class="list-group">
            {% for event in presentations|get_item:room %}
                <li class="list-group-item"><a href="/presentations/{{ event.id }}">{{ event.datetime }} - {{ event.room }} - {{ event.title }}</a></li>
            {% empty %}
                <li><a style="color: white">No presentations yet.</a></li>
            {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

templates/presentation_create.html
{% extends 'base.html' %}
{% block title %} Editing Presentation{% endblock %}
{% block rightbar %}
    <li style="float:right" class="bar_element"><a class="active" >Signed as {{ user.username }}</a></li>
    <li style="float:right" class="bar_element"><a href="{% url 'logout' %}">Sign Out</a></li>
{% endblock %}
{% block styles %}
    label{
  color: white;
    }

{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/presentation_update.html
{% extends 'index.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

templates/presentation_view.html
{% extends 'index.html' %}
{% block title %}Presentation {{ object.title }}{% endblock %}
{% block rightbar %}

    <li style="float:right" class="bar_element"><a class="active" href="#">Signed as {{ user.username }}</a></li>
    <li style="float:right" class="bar_element"><a href="{% url 'logout' %}">Sign Out</a></li>
    {% if author %}
         <li style="float:right" class="bar_element"><a href="/presentations/{{ object.id }}/edit">Edit this presentation</a></li>
        {% else %}
        {% if can_attend and not signed_up %}
            <li style="float:right" class="bar_element"><a href="/presentations/{{ object.id }}/signup">Sign up for this presentation</a></li>
        {% endif %}
        {% if  signed_up %}
            <li style="float:right" class="bar_element"><a>You are signed up for this event</a></li>
        {% endif %}
    {% endif %}
    {% if creator  %}
        <li style="float:right" class="bar_element"><a href="/presentations/create">Create presentation</a></li>
        <li style="float:right" class="bar_element"><a href="/presentations/my">My presentations</a></li>
        {% endif %}
{% endblock %}
{% block styles %}
form{
    text-align: center;
}
www.ibrahimjabbari.com */
@import url(https://fonts.googleapis.com/css?family=Arvo:700);
@import url(https://fonts.googleapis.com/css?family=Seaweed+Script);
body {
  background-color: #222;
}
.plate {
  width: 410px;
  margin: 10% auto;
}
.shadow {
  color: #fff;
  font-family: Arvo;
  font-weight: bold;
  text-shadow:
    -3px -3px 0 #222,
    3px -3px 0 #222,
    -3px 3px 0 #222,
    3px 3px 0 #222,
    4px 4px 0 #fff,
    5px 5px 0 #fff,
    6px 6px 0 #fff,
    7px 7px 0 #fff;
  line-height: 0.8em;
  letter-spacing: 0.1em;
  transform: scaleY(0.7);
  -webkit-transform: scaleY(0.7);
  -moz-transform: scaleY(0.7);
  margin:0;
  text-align: center;
}
    .text {
        font-size: 60px;
        color:#fff;
        text-align:center;
    }
    .description {
        font-size: 35px;
        text-align:center
    }
    .text3 {
        font-size: 100px;
    }
    pre {
        display: block;
        padding: 9.5px;
        margin: 0 0 10px;
        font-size: 13px;
        line-height: 1.42857143;
        color: #333;
        word-break: break-all;
        word-wrap: break-word;
        background-color: #f5f5f5;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
    .alert {
        font-size: 25px;
        text-align:center;
        color: darkred;
    }
{% endblock %}
{% block content %}
    <div class="container">
        <div class="fb-profile">
                <div class="fb-profile-text">
                    <h1 class="shadow text3">{{ object.title }}</h1><br>
                    <pre style="font-size: 20px;">{{ object.description }}</pre>
                    <p  class="text">Presenters:
                        {%  for presenter in presenters%}
                        <a style="color: #009933" href="/profile/{{ presenter.id }}"> {{ presenter }}</a>
                    {% endfor %}</p>
                    <p  class=" text" >Where: {{ object.room.number }} at {{ object.room.address }}</p>
                    <p  class=" text">When: {{ object.datetime }}</p>
                    <p style="text-align: right;font-size: 30px" class="text">Listeners now: {{ object.profile_set.count }}</p>
     {% if not author  %}
        {% if not can_attend %}
            <p class="alert">You can no longer register for this event.</p>
        {% endif %}
    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/presentations_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

    <div class="container">
  <h2>{{ name }}</h2>


<ul class="list-group">
{% for event in object_list %}
    <li class="list-group-item"><a href="/presentations/{{ event.id }}">{{ event.datetime }} - {{ event.room }} - {{ event.title }}</a></li>
{% empty %}
    <li><a style="color: white">No presentations yet.</a></li>
{% endfor %}
</ul>
    </div>
{% endblock %}

templates/profile_update.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</div>
{% endblock %}

templates/profile_view.html
{% extends 'index.html' %}
{% block title %}
    My profile
{% endblock %}
{% block rightbar %}
    {{ block.super }}
    {% if profile.user.id == user_id %}
    <li style="float:right" class="bar_element"><a href="/profile/edit">Edit profile</a></li>
    {% endif %}
{% endblock %}

{% block content %}

<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <div class="container">
        <div class="fb-profile">
            <div class="fb-profile-text">
                <h1 style="text-align: center;color: white">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
                <h1 style="color: whitesmoke; text-align: left;font-size: 20px">Birthdate: {{ profile.birth_date }}</h1>
                <h1 style="text-align: center;color: white"> @{{ profile.user.username }}</h1>
                <pre>Bio: {{ profile.bio }}</pre>

            </div>
        </div>
    </div>
    <div class="container">
    {% if creator %}
        <h2 style="color: white">Presenter on these events:</h2>
                  <ul class="list-group">
                {% for event in author_events %}
                    <li class="list-group-item"><a href="/presentations/{{ event.id }}">{{event.title}} by {{ event.presenter}} at {{event.datetime}}</a></li>
                {% endfor %}
                  </ul>
    {% endif %}
    </div>
    <div class="container">
        <h2 style="color: white">Will visit these events:</h2>
                  <ul class="list-group">
                {% for event in events %}
                    <li class="list-group-item"><a href="/presentations/{{ event.id }}">{{event.title}} by {{ event.presenter}} at {{event.datetime}}</a></li>
                {% endfor %}
                  </ul>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}
Registration
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}